# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies with caching
COPY package.json package-lock.json tsconfig.json smithery.yaml ./
COPY src ./src
COPY scripts ./scripts

# Install and build
RUN npm ci --ignore-scripts && \
    npm run build

# Default entrypoint
ENTRYPOINT ["node", "build/index.js"]
